# Numpy 함수

# 하나의 array에 적용 (단항 유니버셜 함수)

유니버셜 함수 : ndarray안에 있는 데이터의 요소별로 연산을 수행해주는 함수

In [ ]:
import numpy as np

ar1 = np.random.randn(5, 3)
ar1

array([[ 1.40800844,  0.03135063, -0.09400188],
       [ 0.28450886,  1.43702308, -0.83020111],
       [ 0.25970173,  0.75636304, -0.10644104],
       [ 0.04043692, -0.39796911,  0.61683807],
       [-1.2347263 ,  1.56928417,  1.85325622]])

In [ ]:
# 각 요소의 절대값
np.abs(ar1)

array([[1.40800844, 0.03135063, 0.09400188],
       [0.28450886, 1.43702308, 0.83020111],
       [0.25970173, 0.75636304, 0.10644104],
       [0.04043692, 0.39796911, 0.61683807],
       [1.2347263 , 1.56928417, 1.85325622]])

In [ ]:
# 각 요소의 제곱근 계산 ( == ar1 ** 0.5)
np.sqrt(ar1)

<ipython-input-6-bcb70e1b9820>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar1)


array([[1.18659532, 0.17706109,        nan],
       [0.53339372, 1.19875898,        nan],
       [0.50960939, 0.86969135,        nan],
       [0.20108932,        nan, 0.78539039],
       [       nan, 1.25271073, 1.36134353]])

In [ ]:
# 각 요소의 제곱 계산
np.square(ar1)

array([[1.98248778e+00, 9.82862087e-04, 8.83635282e-03],
       [8.09452913e-02, 2.06503534e+00, 6.89233879e-01],
       [6.74449882e-02, 5.72085050e-01, 1.13296948e-02],
       [1.63514418e-03, 1.58379410e-01, 3.80489202e-01],
       [1.52454902e+00, 2.46265282e+00, 3.43455860e+00]])

In [ ]:
# 각 요소를 자연로그, 상용로그, 아래가 2인 로그를 씌운 값 계산
print(np.log(ar1))
print()
print(np.log10(ar1))
print()
print(np.log2(ar1))

[[ 0.34217625 -3.46252087         nan]
 [-1.25699088  0.36257367         nan]
 [-1.3482215  -0.27923381         nan]
 [-3.20801215         nan -0.48314874]
 [        nan  0.45061958  0.61694421]]

[[ 0.14860526 -1.50375371         nan]
 [-0.5459042   0.15746374         nan]
 [-0.58552516 -0.1212697          nan]
 [-1.39322197         nan -0.20982883]
 [        nan  0.1957016   0.26793547]]

[[ 0.49365599 -4.99536169         nan]
 [-1.81345452  0.52308324         nan]
 [-1.94507247 -0.40284923         nan]
 [-4.62818322         nan -0.69703629]
 [        nan  0.65010663  0.89006235]]


<ipython-input-8-9ac07f5d57b3>:2: RuntimeWarning: invalid value encountered in log
  print(np.log(ar1))
<ipython-input-8-9ac07f5d57b3>:4: RuntimeWarning: invalid value encountered in log10
  print(np.log10(ar1))
<ipython-input-8-9ac07f5d57b3>:6: RuntimeWarning: invalid value encountered in log2
  print(np.log2(ar1))


In [ ]:
# 각 요소의 부호 나타내기 (+ : 1, - : -1, 0 : 0)
np.sign(ar1)

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.]])

In [ ]:
# 각 요소의 소수 첫번째 자리에서 올림한 값 계산
np.ceil(ar1)

array([[ 2.,  1., -0.],
       [ 1.,  2., -0.],
       [ 1.,  1., -0.],
       [ 1., -0.,  1.],
       [-1.,  2.,  2.]])

In [ ]:
# 각 요소의 소수 첫번째 자리에서 버림한 값 계산
np.floor(ar1)

array([[ 1.,  0., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -1.],
       [ 0., -1.,  0.],
       [-2.,  1.,  1.]])

In [ ]:
# 각 요소의 소수 첫번쨰 자리에서 반올림한 값 계산
np.round(ar1)

array([[ 1.,  0., -0.],
       [ 0.,  1., -1.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.],
       [-1.,  2.,  2.]])

In [ ]:
# 각 요소가 nan인 경우 True, 아닌 경우 False를 반환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False를 반환
np.isinf(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# 각 요소에 대해 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)
# ~h : 쌍곡선 함수
# 쌍곡선 : 고정된 두 초점으로부터 거리가 일정한 점들에 의해 나타나는 곡선
np.cos(ar1)

array([[ 0.16206986,  0.99950861,  0.99558508],
       [ 0.95979962,  0.13337461,  0.67472734],
       [ 0.96646661,  0.72733679,  0.9943405 ],
       [ 0.99918254,  0.92184996,  0.81571158],
       [ 0.32977953,  0.00151215, -0.2787189 ]])

# 두 개의 array에 적용 (이항 유니버셜 함수)

In [ ]:
ar1

array([[ 1.40800844,  0.03135063, -0.09400188],
       [ 0.28450886,  1.43702308, -0.83020111],
       [ 0.25970173,  0.75636304, -0.10644104],
       [ 0.04043692, -0.39796911,  0.61683807],
       [-1.2347263 ,  1.56928417,  1.85325622]])

In [ ]:
ar2 = np.random.randn(5, 3)
ar2

array([[ 1.78594416,  1.62036958,  0.70449808],
       [ 1.35559126, -0.30254703, -0.24584154],
       [ 1.03920825,  0.41350892,  0.30115523],
       [ 0.87653472, -0.26894622, -0.3136663 ],
       [-0.4857791 , -1.74094577,  0.1086726 ]])

In [ ]:
# 두 개의 array에 대해 동일한 위치 요소끼리
# 연산 값을 계산함수 (add, subtract, multiply, divide)
np.multiply(ar1, ar2)

array([[ 2.51462446,  0.05079961, -0.06622414],
       [ 0.38567772, -0.43476706,  0.20409792],
       [ 0.26988418,  0.31276286, -0.03205528],
       [ 0.03544436,  0.10703229, -0.19348131],
       [ 0.59980423, -2.73203865,  0.20139817]])

In [ ]:
# 두 개의 array에 대해 동일한 위치의 요소끼리 비교해서 최대값 or 최소값 계산
#   (maximum, minimum)
np.maximum(ar1, ar2)

array([[ 1.78594416,  1.62036958,  0.70449808],
       [ 1.35559126,  1.43702308, -0.24584154],
       [ 1.03920825,  0.75636304,  0.30115523],
       [ 0.87653472, -0.26894622,  0.61683807],
       [-0.4857791 ,  1.56928417,  1.85325622]])

# 통계 함수

통계 함수를 통해서 array의 합이나 평균 등을 구할 때

추가로 'axis'라는 파라미터에 대한 값을 지정해서

열 또는 행의 합 또는 평균 등을 구할 수 있음 !

In [1]:
# 열 간의 합을 계산
np.sum(ar1, axis=0)

NameError: name 'np' is not defined

In [ ]:
# 행 간의 합을 계산
np.sum(ar1, axis=1)

In [ ]:
# 전체 요소의 평균을 계산
np.mean(ar1)

In [ ]:
# 전체 요소의 표준편차, 분산, 최소값, 최대값 (std, var, min, max)
# 표준편차 : 데이터가 평균으로부터 얼마나 흩어져있는지를 나타내는 지표
# 분산 : 데이터가 평균으로부터 얼마나 멀리 떨어져있는지를 측정하는 지표
np.std(ar1)

In [ ]:
# 전체 요소의 최소값, 최대값이 위치한 인덱스의 위치를 반환 (argmin, argmax)
np.argmin(ar1)

In [ ]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산 (cumsum, cumprod)
np.cumsum(ar1)

In [ ]:
# 사분위수 : 사분위수는 데이터를 4등분 한 것

# 0.25 : 1 사분위수 / 0.5 : 2 사분위수 (중앙값) / 0.75 : 3 사분위수
np.quantile(ar1, [0.25, 0.5, 0.75])

# 기타 함수

In [ ]:
# 전체 요소에 대해서 오름차순 정렬
np.sort(ar1)

array([[-0.09400188,  0.03135063,  1.40800844],
       [-0.83020111,  0.28450886,  1.43702308],
       [-0.10644104,  0.25970173,  0.75636304],
       [-0.39796911,  0.04043692,  0.61683807],
       [-1.2347263 ,  1.56928417,  1.85325622]])

In [ ]:
# 열 방향으로 오름차순 정렬
np.sort(ar1, axis=0)

array([[-1.2347263 , -0.39796911, -0.83020111],
       [ 0.04043692,  0.03135063, -0.10644104],
       [ 0.25970173,  0.75636304, -0.09400188],
       [ 0.28450886,  1.43702308,  0.61683807],
       [ 1.40800844,  1.56928417,  1.85325622]])

In [ ]:
# zip 함수
# 각 객체들을 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
numbers = [1, 2, 3]
letters = ['A', 'B', 'C']
for pair in zip(numbers, letters):
    print(pair)

(1, 'A')
(2, 'B')
(3, 'C')
